### ISSUE TITLE
Indicate to Mod Menu that Kotlin is a library

### ISSUE THREAD

**Issue by matthew-cline** [FabricMC/fabric-language-kotlin#15] opened 2019-11-24 09:57 UTC
The latest version of [Mod Menu (Fabric](https://www.curseforge.com/minecraft/mc-mods/modmenu) allows a mod to indicate that the mod is a library for other mods, so that libraries can be hidden from the list of mods.  The Kotlin mod should use this, since right now it shows up 4 to 5 times in the mod list.

**Comment by natanfudge** [comment] 2019-11-24 09:58
Why is is being shown 5 times?! Loader is supposed to only load the latest version.

**Comment by Juuxel** [comment] 2019-11-24 09:59
I think it shows the JIJ'd Kotlin libraries as separate mods.

**Comment by natanfudge** [comment] 2019-11-24 10:00
But it's still supposed to only load one... Unless modmenu gets the information in a way that doesn't correspond to what mods are actually loaded.

**Comment by Juuxel** [comment] 2019-11-24 10:10
FLK is marked as a library already, but the JIJ'd submodules aren't (their mod metadata is generated during the build process).

https://github.com/FabricMC/fabric-language-kotlin/blob/bd38e8bce93043b83c36da6721694de4b0860960/src/main/resources/fabric.mod.json#L21-L23

![jars-in-jar](https://user-images.githubusercontent.com/6596629/69493101-2b808800-0eb3-11ea-86e5-f989e45f620e.png)

**Comment by modmuss50** [comment] 2019-11-24 11:04
This should be handled in mod menu untill there is a none modmenu specfic way of doing this.

**Comment by shedaniel** [comment] 2019-11-24 11:06
Just make a custom value called `fabric:custom` or whatever that doesn't have that modmenu namespace?

**Comment by Juuxel** [comment] 2019-11-24 13:30
The problem is that those libraries have fabric.mod.jsons generated by Loom, so currently there's no way to set `modmenu:api`/`fabric:library`/whatever there.

**Comment by NikkyAI** [comment] 2019-11-30 22:53
i did not want to modify the jars pulled from maven, as this could break checksums or signing, do we really need to do this ?
can this be defined externally in a simple way ?

**Comment by shedaniel** [comment] 2019-12-01 01:37
Doesn't loom already add the fabric.mod.json by including non-mods?

**Comment by Sollace** [comment] 2019-12-01 05:57
The JiJ process can just automatically include a `mod:jij` in the automatically generated fabric.mod.json.

If a jar already has one, I don't think the build script should be removing/changing them though. :/

**Comment by Sollace** [comment] 2019-12-01 06:00
Also maybe modmenu needs to change its behaviour so that any jij jars found inside a mod marked as a library are hidden as well.

**Comment by Prospector** [comment] 2019-12-15 18:25
There's no real way to determine what mod used to be JIJ'd because they're all loaded the same

**Comment by Domaman202** [comment] 2020-12-19 14:53
Let's close this issue as it is no longer relevant

**Comment by modmuss50** [comment] 2021-02-04 19:24
This has been resolved I believe

**Closed by modmuss50** 2021-02-04 19:24 UTC

**Comment by Madis0** [comment] 2021-11-23 17:58
This issue is again present on (at least) v1.7.0.

**Comment by Juuxel** [comment] 2021-11-23 18:22
Yeah, since the `modmenu:api` marker was removed, the included Kotlin libraries are properly marked now and FLK itself isn't.
