### ISSUE TITLE
Beta 1.10.11 OptiGUI incompatibility

### ISSUE THREAD

**Issue by Ch4mp10** [FabricMC/fabric-language-kotlin#123] opened 2023-11-02 13:11 UTC
Beta 1.10.11 of Fabric Language Kotlin causes OptiGUI 2.1.5 + 2.1.6 to crash
[crash-2023-11-02_08.53.58-client.txt](https://github.com/FabricMC/fabric-language-kotlin/files/13239089/crash-2023-11-02_08.53.58-client.txt)
[crash-2023-11-02_08.58.39-client.txt](https://github.com/FabricMC/fabric-language-kotlin/files/13239090/crash-2023-11-02_08.58.39-client.txt)
[crash-2023-11-02_09.00.26-client.txt](https://github.com/FabricMC/fabric-language-kotlin/files/13239091/crash-2023-11-02_09.00.26-client.txt)

**Comment by modmuss50** [comment] 2023-11-02 13:12
Duplicate of: https://github.com/FabricMC/fabric-language-kotlin/issues/120

This has already been fixed, please update Fabric Language Kotlin to 1.10.12 or later.

**Closed by modmuss50** 2023-11-02 13:12 UTC
