### ISSUE TITLE
Crash with version fabric-language-kotlin-1.3.31+build.3

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric-language-kotlin#9] opened 2019-05-29 02:03 UTC
https://paste.ee/p/CX3pW

Going back to fabric-language-kotlin-1.3.30+build.2 solves the problem.

**Comment by el0c** [comment] 2019-05-29 03:51
Happens with no other mods installed besides FabricAPI:

https://pastebin.com/7Y3bpWy8

**Comment by magneticflux-** [comment] 2019-05-30 00:11
Same. Caused by jar-in-jar not working properly?
[MultiMC log](https://paste.ee/p/ERqO4)

**Comment by modmuss50** [comment] 2019-05-30 00:16
I have archived the file on curse, @NikkyAI when you get a chance mind taking a look at this?

**Comment by NikkyAI** [comment] 2019-05-30 12:34
seems like moving to jar-in-jar did not work as intended, might it be that the language adapter itself requires stuff to be shadowed ?
weird that it seemed to work for me

**Comment by NikkyAI** [comment] 2019-05-30 12:58
yeah the problem seemed to have been that i overlooked one dependency, shadowJar added it transiently and jar-in-jar does not
this also explains the filesize difference, should be fixed in `build.4`
i tested in multimc with the following mods: 
- modmenu@1.5.4-85
- fabric@0.2.7+build.127
- fabricloader@0.4.8+build.154
- fabric-language-kotlin@1.3.31+local
- kotlin-test@1.3.31
and apart from flooding modmenu with all the library entries.. it seems to work fine

**Closed by NikkyAI** 2019-05-30 12:58 UTC
